/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CaptureSession {
  pid: number
  process_name: string
  is_capture_active: boolean
}
export interface WindowContext {
  pid: number
  title: string
  is_focused: boolean
}
export interface HardwareSnapshot {
  is_available: boolean
  unavailable_reason?: string
  sessions: Array<CaptureSession>
  windows: Array<WindowContext>
  device_running_somewhere: boolean
  captured_at: string
}
export declare function pollCaptureSessions(): Promise<HardwareSnapshot>
